### ISSUE TITLE
Bad fps with some games with AMD APU A6 7400k

### ISSUE THREAD

**Issue by jojo9092** [jackun/openencodevfw#23]
There is a major problem that never effected me before but now its doing it, trying to record some games at any settings and resolution, fullscreen or windowed, disabling desktop effects and areo, the fps of the game and worse, the write fps is really bad. My hard drive has enough speed (100mb/s) to record and my cpu should run ok with it since it did when the issue was not there.
For example, trying to run battlefield 3 and recording it will cause the fps to bog down on the game and but the writing fps is even lower than usual. But when I unfocused the game like click on dxtory window the fps jumps right up and the game fps is now equaling the write fps.
Using the codec on dxtory with all setting set to default, have tried setting fps higher but no effect.
Opencl disabled and enabled, tried all levels of quality and use CBR VBR and QP at different bitrates.
Playing a simple unity game works at 60fps no problem, this issue is effecting Crysis 2, Crysis 3, Furmark, bf3, bf4 from what I have gathered.
Please help me with this issue, it just started to happen out of no where.

Specs and what have I tried....
Windows 64bit
AMD A6 7400k as cpu and gpu (Does support VCE with programs like the VCE build of OBS)
Reinstalled dxtory and openencodevfw
Updated all the Microsoft c++
Used AMD drivers 13.10 and current 14.10 but no change
Overclocked gpu and cpu and tried with stock clocks too but no change.
Reset bios, no change.

**Comment by jackun** [comment]
> Please help me with this issue, it just started to happen out of no where.

Erhm, sorry, I'm no witch doctor. You can try the ["null" codec](https://dl.dropboxusercontent.com/u/235773/nullvfw.7z) to remove encoding overhead from the equation though.
