### ISSUE TITLE
Render at 1152p?

### ISSUE THREAD

**Issue by Xeonmeister** [jackun/openencodevfw#24]
After i had installed the openencodevfw i noticed, that i can use it for rendering in sony vegas. It works fine with 1080p, but the problem is that i want to render my videos at 2048x1152, and if i try this it says:
'no compatible video codec was found'
I guess that 1920x1080 is the maximum resolution that i can use, but is there a way to render at 2048x1152?

**Comment by jackun** [comment]
No, probably not with openVideo API and definitely not with any VCE before Tonga.
But Tonga and new yet unreleased R9 3xx cards should work with AMF API, probably. I'll might start a VFW-based [AMF](http://developer.amd.com/tools-and-sdks/media-sdk/) codec if there's a need.
