### ISSUE TITLE
Distortion while cropping

### ISSUE THREAD

**Issue by d4m4in** [jackun/openencodevfw#25]
While using null transform in VirtualDub, exported file is like in rhombus shape, and with disorted colors. Without null transform everything is great. I found out in your configuration files "encCropLeftOffset to encCropBottomOffset" but I don't really know where to find these files on my pc to edit these values.

**Comment by jackun** [comment]
Refresh my memory, `null transform`? Screenshot?

**Comment by d4m4in** [comment]
This is the option i was talking of: VirtualDub>Video>Filters>Null Transform 
![1st](https://cloud.githubusercontent.com/assets/12970336/8264568/fd616240-16e7-11e5-8b7a-16d1333ea8bf.PNG)

And this is how does looks distorted video:
![2n](https://cloud.githubusercontent.com/assets/12970336/8264571/047c6b60-16e8-11e5-98ae-396fdf9ade7e.PNG)

**Comment by jackun** [comment]
So it seems BMP aligns scanline to DWORD (4 bytes) and as such it may add up to 3 (useless) bytes to a scanline. OpenCL path should work now, but needs stripping of the extra bytes so the fastest would be to force the use 32 bit color depth. Now I remember I forgot the make the cpu conversion account for these extra bytes.
