### ISSUE TITLE
Encoder not showing up (32bit and 64bit)

### ISSUE THREAD

**Issue by DieWeiseEule** [jackun/openencodevfw#28]
Hi

Wanted to just load the VFW-interface to see, what options the encoder offers, but can't see it in any program (tried Bandicam, VDub32 and Vdub64).

Do I need to have an AMD card already installed (or the driver) to actually be able to see it, or should it already show up?
I already installed the MSVC++ 2013 runtimes.
Encoder installed everything without any errors (I ran it as admin).
(OS is Windows 8.1 64bit.)

I will have and AMD card in a few days, and want to test this encoder to see if I'll keep it.
But maybe someone can already answer this question:
Is it possible to encode a lossless 1080p/60fps stream with an R9 390 with this encoder?
(Not to stream, but to save on an HDD.)

**Comment by jackun** [comment]
This version is deprecated, only works with pre-15.7 drivers. [https://github.com/jackun/TestAMFVFW](Go here.)

But you can run the configuration dialog  from command line (in case of TestAMFVFW): `rundll32 TestAMFVFW.dll,Configure` (if i remembered to add)

**Comment by DieWeiseEule** [comment]
Ah, ok. Thx!
Will check this out.
