### ISSUE TITLE
TestAMFVFW showing up in Sherlock but not in Dxtory.

### ISSUE THREAD

**Issue by HadiKiwi** [jackun/openencodevfw#29]
I have re-installed CCC 15.7.1 like ten times now and AMF isn't showing up in Dxtory. It does show up in Sherlock though. Can I have some instructions and help for dummies? I'm kind of new to this since I started using VFW 3 months ago. Any help would be seriously appreciated.

**Comment by jackun** [comment]
Dunno. Just did fresh install of windows, all shows up OK.
Try DepWalker on testamfvfw.dlls, [see here](https://github.com/jackun/openencodevfw/issues/17#issuecomment-59406014) or check if it finds the runtime dlls with [ProcMon](https://technet.microsoft.com/en-us/sysinternals/bb896645.aspx) and set options to "Path" "contains" "TestAMFVFW", [see here for random example image](http://www.supportnet.de/articleimage/2340935/02-Vollversionen-von-Microsoft-Process-Monitor-Filter-einstellen.png)

**Comment by HadiKiwi** [comment]
It doesn't really look like that. What should I do?

**Comment by HadiKiwi** [comment]
It does look like it except thereally is another file with the function "Configure" while the one in the example had only "DriverProc"

**Comment by HadiKiwi** [comment]
Hmmm... TESTAMFVFW is showing up on Bandicam yet it isn't showing up on Dxtory. I guess I need to re-install Dxtory.

**Comment by jackun** [comment]
In case you didn't, download it again. I added some more registry entries in case with the 32bit-on-64bit than plain 64bit or 32bit etc differences make it not find the AMF's runtime files.

**Comment by HadiKiwi** [comment]
It worked after re-installing Dxtory and adding that Path in ProcMon. Thanks man! Keep up the great work. :dart: 

EDIT: Any donations link?
